version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run dev'
    restart: always
    container_name: my_backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    volumes:
      - .:/app
    networks:
      - metrics

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks:
      - metrics
  
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    hostname: grafana
    user: "$UID:$GID"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana:/var/lib/grafana
    networks:
      - metrics

  # bd:
  #   image: postgres:14.1
  #   container_name: postgres-db
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - .database:/var/lib/postgresql/data
  #   networks:
  #     - network


networks:
  metrics:
    driver: bridge
