version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run dev'
    ports:
      - 3000:3000
    volumes:
      - .:/app
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7.22
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: product
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - docker/dbdata:/var/lib/mysql
  #   ports:
  #     - 33066:3306
