global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["0.0.0.0:9090"]
  
  - job_name: 'application'
    scrape_interval: 5s
    static_configs:
      - targets: ['application:5000']