global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["0.0.0.0:9090"]
  
  - job_name: 'my_backend'
    scrape_interval: 5s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['my_backend:5000']